# Generated by Django 5.1.7 on 2025-03-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='상세주소',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='우편번호',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='주소',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='생일',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='전화번호',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
