# Generated by Django 5.2.1 on 2025-05-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0003_dogtype_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='running',
            name='hospital',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='business_hours',
            field=models.CharField(blank=True, default='정보 없음', max_length=255),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='kakao_id',
            field=models.CharField(help_text='카카오 플레이스 ID', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='x',
            field=models.CharField(help_text='경도 (longitude)', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='y',
            field=models.CharField(help_text='위도 (latitude)', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.DeleteModel(
            name='dogtype',
        ),
        migrations.DeleteModel(
            name='running',
        ),
    ]
